### ISSUE TITLE
For check icon, add a warning and red cross for products that may contain and do contain allergens

### ISSUE THREAD

**Issue by juliadeng123** [Michelle2317/GoldiBite#124]
![image](https://github.com/user-attachments/assets/df864f4b-4c04-4b04-8b52-4a55903c0d06)

No Allergens Show:
![Checkmark](https://github.com/user-attachments/assets/06edefab-0e8e-4c7e-a2b2-5c273333fc22)

Allergens Detected:
![Red X](https://github.com/user-attachments/assets/93dc88c1-8b02-4794-a808-61e74b7987d6)

May contain possible Allergens:
![Warning](https://github.com/user-attachments/assets/ca9b5ad8-f9a3-41ce-b082-b8436173b559)

They're in a folder called Menu Translation Icons, In Photos, In the Drive

**Comment by klee616** [comment]
Do you have the logic how to show the icon?

**Comment by juliadeng123** [comment]
Yea, you're right. We don't have a way to show it right now. Since we only have two options to show there is or there isn't allergens. So just keep it this way.
