### ISSUE TITLE
Iphone 16-  when scanning menu the option on to "use image " doesn't pop up

### ISSUE THREAD

**Issue by GavinPahal** [Michelle2317/GoldiBite#136]
![IMG_0155](https://github.com/user-attachments/assets/61cf79ef-4441-4f5e-bfad-d340d6e9b9b1)

**Comment by klee616** [comment]
Andrew have a same issue,
please checkout  142-use-it-button-on-menu-scanner-not-appearing, and let me know the result.
<code>
git checkout 142-use-it-button-on-menu-scanner-not-appearing
git pull
</code>

**Comment by GavinPahal** [comment]
issue is fixed
