### ISSUE TITLE
For selecting gender- the other option selections should be changed to prefer not to say

### ISSUE THREAD

**Issue by GavinPahal** [Michelle2317/GoldiBite#137]
![IMG_0153](https://github.com/user-attachments/assets/086b097c-affb-45f1-9e04-5b18cfd41811)

**Comment by klee616** [comment]
Please check it on 137-for-selecting-gender-the-other-option-selections-should-be-changed-to-prefer-not-to-say
<code>
git checkout 137-for-selecting-gender-the-other-option-selections-should-be-changed-to-prefer-not-to-say
git pull
</code>
![IMG_2855](https://github.com/user-attachments/assets/4b64b50c-26f6-49c4-8ce0-f2b86c37d691)
![IMG_2856](https://github.com/user-attachments/assets/9d314d37-4b63-4496-8227-0d50c08e7e00)

**Comment by GavinPahal** [comment]
branch isn't updated still shows other, doesn't display prefer not to say

**Comment by GavinPahal** [comment]
It works now thanks
