### ISSUE TITLE
DarkMode- in Emergency page clicking the I icon- the text color and close overlay needs to be black font 

### ISSUE THREAD

**Issue by GavinPahal** [Michelle2317/GoldiBite#139]
![IMG_0149](https://github.com/user-attachments/assets/83b961d4-1e29-42a4-b4fb-9b8127071236)

**Comment by klee616** [comment]
please test it 
<code>
git checkout 139-darkmode-in-emergency-page-clicking-the-i-icon-the-text-color-and-close-overlay-needs-to-be-black-font
git pull
</code>

**Comment by GavinPahal** [comment]
Works well now
