### ISSUE TITLE
Settings- Delete the location Page

### ISSUE THREAD

**Issue by GavinPahal** [Michelle2317/GoldiBite#141]
![IMG_0152](https://github.com/user-attachments/assets/b89f3b08-e092-4598-a145-6f1f5ee224ee)

**Comment by klee616** [comment]
Done, Please check it on 141-settings-delete-the-location-page
<code>
git checkout 141-settings-delete-the-location-page
</code>
![IMG_2841](https://github.com/user-attachments/assets/4b1df2e9-89c0-4d87-977f-e04fccd2496d)

**Comment by GavinPahal** [comment]
Works well now
