### ISSUE TITLE
"Use it" Button on Menu Scanner not appearing

### ISSUE THREAD

**Issue by AndrewTuritsa** [Michelle2317/GoldiBite#142]
![IMG_6784](https://github.com/user-attachments/assets/3b597dbd-571b-44c2-bfab-22082b78081b)
![IMG_6783](https://github.com/user-attachments/assets/a9cfd974-5162-4371-806d-488caf4d7cb7)

**Comment by klee616** [comment]
please checkout "142-use-it-button-on-menu-scanner-not-appearing" and try again.
<code>
git checkout 142-use-it-button-on-menu-scanner-not-appearing
git pull
</code>

**Comment by AndrewTuritsa** [comment]
https://github.com/user-attachments/assets/e5594294-ed03-4b4b-8813-4e04bd3bc3e1

"Use it" button now appears for me, but despite trying on several menus, I go to the error page almost right away.
