### ISSUE TITLE
Changing "Admin" to the actual imputed names

### ISSUE THREAD

**Issue by AndrewTuritsa** [Michelle2317/GoldiBite#24]
![image0 (1)](https://github.com/user-attachments/assets/3f08effc-8e9b-43bd-b78d-e732b16ea929)

**Comment by klee616** [comment]
the admin, and kaylie133 is hard code and not get from dataset, I will fix it later.

**Comment by klee616** [comment]
Please check out the main branch, and test it.
Also, the settings is not update, because I just develop a layout and the work flow is not complete.
