### ISSUE TITLE
Onboarding - Missing pages (loading and language)?

### ISSUE THREAD

**Issue by juliadeng123** [Michelle2317/GoldiBite#27]
Where did the first loading page with logo, and language options in the onboarding go?

**Comment by klee616** [comment]
I don't do that page because our application only support english.
The language page will be create when our application support the multiple language.

**Comment by juliadeng123** [comment]
I thought it could be like a fake screen, but we only select english. The others are dummy options.
But if we do remove it, then we'll need to remove that from the settings too. And the first onloading screen will need to use the next button that's on the language page.
And what about the loading page?

**Comment by klee616** [comment]
please checkout 27-onboarding-missing-pages-loading-and-language and check it.

**Comment by juliadeng123** [comment]
The loading page looks good.
For the language page, I am not sure if the changes will look different when you merge it to main. But the heading is on a different height from the next page.

And for the next page, since there's a language page now, it would be good if you could put back the back button in there. So people can go back to the language page like in the Figma.

![Screenshot_20241113_094721_Expo Go](https://github.com/user-attachments/assets/06d2f6ea-2ba1-40e1-86b9-684b608d4a01)


![Screenshot_20241113_094715_Expo Go](https://github.com/user-attachments/assets/00f00854-3303-4e1d-b36a-16cbb8a8e7f2)

**Comment by klee616** [comment]
It is hard to do it, because the layout design is difference.
The Next button was fixed in other branch,
