### ISSUE TITLE
Onboarding - spacing of items

### ISSUE THREAD

**Issue by juliadeng123** [Michelle2317/GoldiBite#28]
Items should have the same amount of vertical gap between, title, image, descp, and the buttons. When switching between the screens, they move around

**Comment by klee616** [comment]
![IMG_2752](https://github.com/user-attachments/assets/e7745853-f9e6-4ce9-bcc3-2fb63581c5cf)
![IMG_2753](https://github.com/user-attachments/assets/a706e177-410e-418a-a0b3-b9c6c4cfb67d)
![IMG_2754](https://github.com/user-attachments/assets/16a5a5e4-616b-4fb1-b299-071769c96e1f)
![IMG_2755](https://github.com/user-attachments/assets/c8012c2d-4580-41f6-8f24-8893f2ae7dae)

**Comment by juliadeng123** [comment]
Nice change
More fixes

Next button is on the left side for my screen, but right on yours. It may have something to do with phone sizes. 
Keeping it on the right side would be best.

Skip button would look better if it looked more centered right under the next button. It is a bit more to the left side right now.

After the change, now the text clips out for the text over 3 lines.

![Screenshot_20241109_222401_Expo Go](https://github.com/user-attachments/assets/c82071f9-3abc-4f63-87b4-7640866152d0)
![Screenshot_20241109_222405_Expo Go](https://github.com/user-attachments/assets/4119b935-604e-4e3b-a951-3b556d28744d)
![Screenshot_20241109_222408_Expo Go](https://github.com/user-attachments/assets/0fbede1a-ec37-4ee8-97d8-10dd01ad78ba)
![Screenshot_20241109_222411_Expo Go](https://github.com/user-attachments/assets/675cea32-a9bc-4633-9fee-866206dce502)

**Comment by klee616** [comment]
I move the skip button little to bit, please check it.
Also, would you create a new issue for 'Next button' on the the left side?

**Comment by klee616** [comment]
I try to adjust the Skip button little to bit. Please check again.

**Comment by juliadeng123** [comment]
Yep looks good, you can merge
