### ISSUE TITLE
Onboarding - Sign up/Sign in

### ISSUE THREAD

**Issue by juliadeng123** [Michelle2317/GoldiBite#29]
Should have error messages if it doesn’t match the format for email

Have sign in/sign up input boxes at same height when switching between the two

Password - can it be made so it doesn’t start with capital when you start typing on the phone?

Sign up 
Two Terms of service on signup
Privacy policy too big

Sign in 
Error says username/password, but input box says email/password.

**Comment by klee616** [comment]
Fixed, please checkout the branch, and test it again.

**Comment by klee616** [comment]
I will try to add the error message when user input the wrong format. 
Would you create a new issues for "email error message", "Sign in with", and "Privacy and policy"? 
So, we can close this issue and merge this branch into main branch. 
I think "email error message", "Sign in with", and "Privacy and policy" is not related , so you might create three issues.

**Comment by juliadeng123** [comment]
Alright I'll separate the issues, you can merge it when you can.
