### ISSUE TITLE
Create Account Process

### ISSUE THREAD

**Issue by juliadeng123** [Michelle2317/GoldiBite#30]
Can’t select icon, or no feedback (no outline when selecting)
Age = number input only
Chips aren’t working? (is it implemented yet)

"contactPhone?" is wrong text for input box

**Comment by klee616** [comment]
I will fix it later, because we need to store the user input, and use that input in the analysis task.

**Comment by klee616** [comment]
I fix some issue in main branch, please test in main branch.
1. the icon can be selected, please check it.
2. I change the Age to drop down list.
3. Would you create a new issue for chips. (I need more time to fixed this issue)
4. the contactPhone is change to " Contact phone"

**Comment by juliadeng123** [comment]
I can't get past the sign up page so I can't see the changes. I am using an android phone but when I tried localhost it didn't work either.

"Contact phone" can be changed to "Phone Number", sorry, I should have been clearer.

https://github.com/user-attachments/assets/f46801df-c3f5-4bdc-9209-f01dfea2d51f

I did get this error as well when I used localhost, not sure if it matters.
![signup error](https://github.com/user-attachments/assets/02aa1aea-139a-42ea-9949-d782ae5302f3)

**Comment by klee616** [comment]
The sign up function doesn't work, and I doesn't have planning to fix it because the login process is not essential factor in this project.
I'll fixed the contact phone to Phone Number in other branch.

**Comment by juliadeng123** [comment]
Does it link to the setupAccount pages in the other branches? The sign-up pages doesn't need to function, but I think it would be good if pressing the Sign Up button can lead to the next page.

**Comment by klee616** [comment]
The contact phone have been updated to main branch.
For the Sign up button, please create the new issue, so we can close this issue if you accept the change.
![IMG_70416146D6DD-1](https://github.com/user-attachments/assets/e89ca8bf-029d-46e0-a8b1-4287f2d5568d)

**Comment by juliadeng123** [comment]
I meant "Contact Phone" should be "Phone Number. It still looks like "Contact Phone" in the main branch.

And I'll make a new issue for the sign up.

![phone](https://github.com/user-attachments/assets/de8e45dc-305c-48a8-89cd-0b39367a7dfd)
