### ISSUE TITLE
fix padding on the sides feel very close to the sides

### ISSUE THREAD

**Issue by leslie179** [Michelle2317/GoldiBite#33]
![image](https://github.com/user-attachments/assets/9c5d9eb1-56fb-431f-8a3d-70463043703e)

**Comment by klee616** [comment]
Please checkout '33-fix-padding-on-the-sides-feel-very-close-to-the-sides' and review it.
git checkout 33-fix-padding-on-the-sides-feel-very-close-to-the-sides
