### ISSUE TITLE
tweak padding  between the top and bottom of chips and the distance between chips and the save button

### ISSUE THREAD

**Issue by leslie179** [Michelle2317/GoldiBite#36]
![image](https://github.com/user-attachments/assets/0a974436-a3e0-4921-8dcb-286174d98975)

**Comment by klee616** [comment]
fixed in the main branch, please check it.
![IMG_2766](https://github.com/user-attachments/assets/66a3719c-85a8-4c49-936c-1569185dbbd7)

**Comment by leslie179** [comment]
thanks
