### ISSUE TITLE
Next button - onboarding 

### ISSUE THREAD

**Issue by juliadeng123** [Michelle2317/GoldiBite#44]
Next button is on the left side for my screen, but right on yours. It may have something to do with phone sizes.
Keeping it on the right side would be best.

![image](https://github.com/user-attachments/assets/1cce3e49-c16a-45db-94f2-4f16ab647973)

**Comment by klee616** [comment]
That issue might fix on main branch, please check it.

**Comment by juliadeng123** [comment]
If you look at issue #27. It'll need a change which will fix this. So you can close this issue now.
