### ISSUE TITLE
"Sign in with" is blurry - sign-in

### ISSUE THREAD

**Issue by juliadeng123** [Michelle2317/GoldiBite#46]
"Sign in with" on login is slightly blurry, may need to have a slightly higher res image.

![image](https://github.com/user-attachments/assets/812cf14d-f31a-4c38-92f3-afd9525c4bf4)

**Comment by klee616** [comment]
Would you provide a high quality image for this task?

**Comment by juliadeng123** [comment]
![sign-in-with](https://github.com/user-attachments/assets/172b0f5f-867d-410e-b1f6-68940e020965)

Try this svg

**Comment by klee616** [comment]
branch: 46-sign-in-with-is-blurry-sign-in 
![IMG_2787](https://github.com/user-attachments/assets/4dd69822-cdb0-4e63-873c-be73f86d9b1b)

**Comment by juliadeng123** [comment]
Looks good
