### ISSUE TITLE
Sign up page

### ISSUE THREAD

**Issue by juliadeng123** [Michelle2317/GoldiBite#58]
Can it link to the setupAccount pages in the other branches? The sign-up pages doesn't need to function, but I think it would be good if pressing the Sign Up button can lead to the next page like the icon page.

And sign in should lead to the home page, not the setupAccount page

**Comment by klee616** [comment]
it will happen the error in create account process, because it do not have database support.
I design the setup process only appearance when the user first-time login.

**Comment by juliadeng123** [comment]
Can it be made so the only function is navigation for now? Instead of having to login everytime with the username and password "a".

What I imagine it to go without a database is:
pressing sign up button -> goes to setup account process
pressing sign in/google/facebook/apple button -> Straight to Home page

At least it would go like this until the database feature is implemented(if there's time)
So it is easier for testing the pages, instead of having to sign in everytime.
The reason I suggested this, is because everytime my browser resets, I need to re-login and this takes time.

**Comment by klee616** [comment]
I pre-input the account information for testing use, so you do not input anything in login process.
