### ISSUE TITLE
Multiple Profiles in Onboarding has changed to Guides

### ISSUE THREAD

**Issue by juliadeng123** [Michelle2317/GoldiBite#83]
The heading and description in onboarding where multiple profiles(the last onboarding stage) was has changed to guides and the guides description. Can check figma.

**Comment by klee616** [comment]
Changed in '84-change-nextback-arrow-buttons-in-guide-to-nextback-buttons-like-the-ones-in-onboarding'
Please check it

**Comment by juliadeng123** [comment]
It still looks like multiple profiles to me

![Screenshot_20241116_003132_Expo Go](https://github.com/user-attachments/assets/7378786d-a18b-4636-aa30-08020c15687d)

**Comment by juliadeng123** [comment]
I can see the change now
