### ISSUE TITLE
Onboarding description cuts out

### ISSUE THREAD

**Issue by juliadeng123** [Michelle2317/GoldiBite#86]
![Screenshot_20241116_003515_Expo Go](https://github.com/user-attachments/assets/cf25b370-ed47-4692-99f3-1809e6660b20)
![Screenshot_20241116_003517_Expo Go](https://github.com/user-attachments/assets/4f0a2a25-d3d7-414f-80e8-7c79af189b7b)
![Screenshot_20241116_003132_Expo Go](https://github.com/user-attachments/assets/3a9749d3-da6a-4f0a-9dab-39c9c500d0e7)

**Comment by klee616** [comment]
Fix on the main branch, please check it.

**Comment by juliadeng123** [comment]
Looks good, thanks
