### ISSUE TITLE
Last page of onboarding has items that has been removed and changed

### ISSUE THREAD

**Issue by juliadeng123** [Michelle2317/GoldiBite#91]
![image](https://github.com/user-attachments/assets/614774ca-e146-40ed-b4b9-9e1ab19a1587)

**Comment by klee616** [comment]
Please check it on 91-last-page-of-onboarding-has-items-that-has-been-removed-and-changed branch.
git switch 91-last-page-of-onboarding-has-items-that-has-been-removed-and-changed
![IMG_2804](https://github.com/user-attachments/assets/1e776c59-4628-4257-b2e4-89265f12f566)

**Comment by juliadeng123** [comment]
I didn't see the 2 "you are all set!". The bottom text would have the name but since we aren't doing that. Just remove the smaller "you are all set!" underneath the icon please.

**Comment by klee616** [comment]
I replace the image please check it
'origin/91-last-page-of-onboarding-has-items-that-has-been-removed-and-changed'.

**Comment by juliadeng123** [comment]
The image was still blurry, so I added the images from my computer. I'll close this issue and merge the branch.
