### ISSUE TITLE
when selected scanner, it goes to barcode but the toggle for Barcode isn't highlight until you press it

### ISSUE THREAD

**Issue by GavinPahal** [Michelle2317/GoldiBite#98]
![IMG_0105 1](https://github.com/user-attachments/assets/f6a83803-238e-4b68-b7ed-1985a908c014)

**Comment by klee616** [comment]
Please checkout 98-when-selected-scanner-it-goes-to-barcode-but-the-toggle-for-barcode-isnt-highlight-until-you-press-it, and test it again
