### ISSUE TITLE
Dark Mode messed up with bright mode in the settings page

### ISSUE THREAD

**Issue by Cindy-tan** [Michelle2317/GoldiBite#99]
![IMG_6877](https://github.com/user-attachments/assets/b5a78864-9931-4663-89e5-dc07120754be)

**Comment by klee616** [comment]
I have updated style in "99-dark-mode-messed-up-with-bright-mode-in-the-settings-page" branch,
please reiver the issue.
<code>
git checkout 99-dark-mode-messed-up-with-bright-mode-in-the-settings-page
git pull
</code>
